### ISSUE TITLE
Using selectors of selecting svg on page.

### ISSUE THREAD

**Issue by ravisuhag** [Causata/svgenie#2]

**Comment by ravisuhag** [comment]
Hi 

is there any way i can use selectors for selecting svg to save ?

**Comment by benrudolph** [comment]
One workaround is to select the element before hand and pass it in as the first argument. The test page has an example: https://github.com/Causata/svgenie/blob/master/test/test.html#L12

**Comment by ravisuhag** [comment]
Thanks, will try it out ..Also i am having one more problem There are few svg elements on which i have applied classes. But saving with svgenie is not rendering styles applied through classes. Is there any workaround for that. P.S. i can not inline all the styles as i am using C3.JS library.

**Comment by benrudolph** [comment]
I had the same issue. I built this tiny jquery plugin to inline the styles for you. Let me know if that helps: https://github.com/benrudolph/jquery.inlinify
